In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/sample_data/heart(in).csv')

In [ ]:
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [ ]:
df['Sex'] = df['Sex'].map({'M':0,'F':1})
df

Age  Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40    0           ATA        140          289          0     Normal   
1     49    1           NAP        160          180          0     Normal   
2     37    0           ATA        130          283          0         ST   
3     48    1           ASY        138          214          0     Normal   
4     54    0           NAP        150          195          0     Normal   
..   ...  ...           ...        ...          ...        ...        ...   
913   45    0            TA        110          264          0     Normal   
914   68    0           ASY        144          193          1     Normal   
915   57    0           ASY        130          131          0     Normal   
916   57    1           ATA        130          236          0        LVH   
917   38    0           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [ ]:
df['ChestPainType'].value_counts()

ChestPainType
ASY    496
NAP    203
ATA    173
TA      46
Name: count, dtype: int64

In [ ]:
df['ChestPainType']= df['ChestPainType'].map({'ATA':0,'NAP':1,'ASY':2,'TA':3})
df

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40    0              0        140          289          0     Normal   
1     49    1              1        160          180          0     Normal   
2     37    0              0        130          283          0         ST   
3     48    1              2        138          214          0     Normal   
4     54    0              1        150          195          0     Normal   
..   ...  ...            ...        ...          ...        ...        ...   
913   45    0              3        110          264          0     Normal   
914   68    0              2        144          193          1     Normal   
915   57    0              2        130          131          0     Normal   
916   57    1              0        130          236          0        LVH   
917   38    0              1        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [ ]:
df['RestingECG'].value_counts()

RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64

In [ ]:
df['RestingECG'] = df['RestingECG'].map({'Normal':0,'ST':1,'LVH':2})
df

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    0              0        140          289          0           0   
1     49    1              1        160          180          0           0   
2     37    0              0        130          283          0           1   
3     48    1              2        138          214          0           0   
4     54    0              1        150          195          0           0   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    0              3        110          264          0           0   
914   68    0              2        144          193          1           0   
915   57    0              2        130          131          0           0   
916   57    1              0        130          236          0           2   
917   38    0              1        138          175          0           0   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [ ]:
df['ExerciseAngina'].value_counts()

ExerciseAngina
N    547
Y    371
Name: count, dtype: int64

In [ ]:
df['ExerciseAngina'] = df['ExerciseAngina'].map({'Y':0,'N':1})
df

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    0              0        140          289          0           0   
1     49    1              1        160          180          0           0   
2     37    0              0        130          283          0           1   
3     48    1              2        138          214          0           0   
4     54    0              1        150          195          0           0   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    0              3        110          264          0           0   
914   68    0              2        144          193          1           0   
915   57    0              2        130          131          0           0   
916   57    1              0        130          236          0           2   
917   38    0              1        138          175          0           0   

     MaxHR  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172               1      0.0       Up             0  
1      156               1      1.0     Flat             1  
2       98               1      0.0       Up             0  
3      108               0      1.5     Flat             1  
4      122               1      0.0       Up             0  
..     ...             ...      ...      ...           ...  
913    132               1      1.2     Flat             1  
914    141               1      3.4     Flat             1  
915    115               0      1.2     Flat             1  
916    174               1      0.0     Flat             1  
917    173               1      0.0       Up             0  

[918 rows x 12 columns]

In [ ]:
df['ST_Slope'].value_counts()

ST_Slope
Flat    460
Up      395
Down     63
Name: count, dtype: int64

In [ ]:
df['ST_Slope'] = df['ST_Slope'].map({'Up':0,'Flat':1,'Down':2})
df

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    0              0        140          289          0           0   
1     49    1              1        160          180          0           0   
2     37    0              0        130          283          0           1   
3     48    1              2        138          214          0           0   
4     54    0              1        150          195          0           0   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    0              3        110          264          0           0   
914   68    0              2        144          193          1           0   
915   57    0              2        130          131          0           0   
916   57    1              0        130          236          0           2   
917   38    0              1        138          175          0           0   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0      172               1      0.0         0             0  
1      156               1      1.0         1             1  
2       98               1      0.0         0             0  
3      108               0      1.5         1             1  
4      122               1      0.0         0             0  
..     ...             ...      ...       ...           ...  
913    132               1      1.2         1             1  
914    141               1      3.4         1             1  
915    115               0      1.2         1             1  
916    174               1      0.0         1             1  
917    173               1      0.0         0             0  

[918 rows x 12 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
df[['Age',	'Sex',	'ChestPainType','RestingBP','Cholesterol','FastingBS','RestingECG','MaxHR','ExerciseAngina','Oldpeak','ST_Slope'	]]= sc.fit_transform(df[['Age',	'Sex',	'ChestPainType',	'RestingBP',	'Cholesterol',	'FastingBS',	'RestingECG','MaxHR','ExerciseAngina','Oldpeak','ST_Slope'	]])
df.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  \
0  0.244898  0.0       0.000000       0.70     0.479270        0.0   
1  0.428571  1.0       0.333333       0.80     0.298507        0.0   
2  0.183673  0.0       0.000000       0.65     0.469320        0.0   
3  0.408163  1.0       0.666667       0.69     0.354892        0.0   
4  0.530612  0.0       0.333333       0.75     0.323383        0.0   

   RestingECG     MaxHR  ExerciseAngina   Oldpeak  ST_Slope  HeartDisease  
0         0.0  0.788732             1.0  0.295455       0.0             0  
1         0.0  0.676056             1.0  0.409091       0.5             1  
2         0.5  0.267606             1.0  0.295455       0.0             0  
3         0.0  0.338028             0.0  0.465909       0.5             1  
4         0.0  0.436620             1.0  0.295455       0.0             0

In [ ]:
X = df[['Age',	'Sex',	'ChestPainType',	'RestingBP',	'Cholesterol',	'FastingBS',	'RestingECG','MaxHR','ExerciseAngina','Oldpeak','ST_Slope'	]]
y = df[['HeartDisease']]

In [ ]:
print(X.shape)
print(y.shape)

(918, 11)
(918, 1)


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:

from keras import Sequential
from keras.layers import Dense,Dropout
from keras.callbacks import EarlyStopping,ModelCheckpoint
model = Sequential()
model.add(Dense(units=7,input_dim=11,kernel_initializer='random_uniform',activation='relu'))
model.add(Dense(units=20,kernel_initializer='he_uniform',activation='relu'))
model.add(Dense(units=34,kernel_initializer='he_uniform',activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units=60,kernel_initializer='he_uniform',activation='relu'))
model.add(Dense(units=20,kernel_initializer='he_uniform',activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(units=15,kernel_initializer='he_uniform',activation='relu'))
model.add(Dense(units=4,kernel_initializer='he_uniform',activation='relu'))
model.add(Dense(units=1,kernel_initializer='he_uniform'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(loss='mean_square_error',optimizer='adam',metrics=['mse'])

In [ ]:
early_stop = EarlyStopping(
    monitor='val_precision',
    patience = 5,
    restore_best_weights=True,
    verbose=1
)

In [ ]:
checkpoint = ModelCheckpoint(
    'best_model.keras', #.keras is better than h5
    monitor='val_precision',
    verbose=1,
    save_best_only=True
)

In [ ]:
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['precision'])

In [ ]:
model.fit(x_train,y_train,epochs=100,batch_size=20,verbose=1,callbacks=[early_stop,checkpoint],validation_split=0.5)

Epoch 1/100
13/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.5257 - precision: 0.0000e+00 
Epoch 1: val_precision improved from inf to 0.00000, saving model to best_model.keras
19/19 ━━━━━━━━━━━━━━━━━━━━ 9s 87ms/step - loss: 0.5218 - precision: 0.0000e+00 - val_loss: 0.4137 - val_precision: 0.0000e+00
Epoch 2/100
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3249 - precision: 0.3948    
Epoch 2: val_precision did not improve from 0.00000
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.3229 - precision: 0.4088 - val_loss: 0.2121 - val_precision: 0.5971
Epoch 3/100
 8/19 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.2294 - precision: 0.5528
Epoch 3: val_precision did not improve from 0.00000
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.2204 - precision: 0.6029 - val_loss: 0.1757 - val_precision: 0.8408
Epoch 4/100
 1/19 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1331 - precision: 0.9091
Epoch 4: val_precision did not improve from 0.00000
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step -

In [ ]:
loss,accuracy = model.evaluate(x_test,y_test)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1257 - precision: 0.8518 


In [ ]:
loss

0.13611087203025818

In [ ]:
accuracy

0.8666666746139526

In [ ]:
import numpy as np
arr = [[1,2,3,4],[5,6,7,8],[9,0,1,2]]
np_arr = np.array(arr)
print(np_arr.shape)
print(np_arr.ndim)

(3, 4)
2


In [ ]:
np_arr.reshape(6,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0],
       [1, 2]])

In [ ]:
np_arr.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [ ]:
np_arr.reshape(12,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [ ]:
np_arr.reshape(3,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 0],
        [1, 2]]])

In [ ]:
24*24

576

In [ ]:
1920*1080*3

6220800